// Website Monitor - Main Script
// Uses Claude AI to generate intelligent status reports
// Supports up to 20 sites + Telegram delivery

import fetch from "node-fetch";

// ─── CONFIG ────────────────────────────────────────────────────────────────
const WEBSITES = JSON.parse(process.env.WEBSITES || "[]");
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;
const REPORT_TIME = process.env.REPORT_TIME || "morning";

// ─── CHECK WEBSITE ──────────────────────────────────────────────────────────
async function checkWebsite(url) {
  const start = Date.now();
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);
    const res = await fetch(url, {
      method: "GET",
      signal: controller.signal,
      headers: { "User-Agent": "WebsiteMonitor/1.0" },
    });
    clearTimeout(timeout);
    const duration = Date.now() - start;
    return { url, status: res.status, ok: res.ok, responseTime: duration, error: null };
  } catch (err) {
    return { url, status: null, ok: false, responseTime: Date.now() - start, error: err.message };
  }
}

// ─── CHECK ALL WEBSITES ─────────────────────────────────────────────────────
async function checkAll() {
  console.log(`Checking ${WEBSITES.length} websites...`);
  // Run in batches of 10 to avoid flooding
  const results = [];
  for (let i = 0; i < WEBSITES.length; i += 10) {
    const batch = WEBSITES.slice(i, i + 10);
    const batchResults = await Promise.all(batch.map(checkWebsite));
    results.push(...batchResults);
  }
  return results;
}

// ─── GENERATE REPORT WITH CLAUDE ────────────────────────────────────────────
async function generateReport(results) {
  const downSites = results.filter((r) => !r.ok);
  const upSites = results.filter((r) => r.ok);
  const avgResponse = upSites.length
    ? Math.round(upSites.reduce((a, r) => a + r.responseTime, 0) / upSites.length)
    : 0;

  const summary = results
    .map(
      (r) =>
        `${r.url}: ${r.ok ? "UP" : "DOWN"} | HTTP ${r.status || "N/A"} | ${r.responseTime}ms${r.error ? ` | ${r.error}` : ""}`
    )
    .join("\n");

  const prompt = `You are a website monitoring assistant. Generate a concise Telegram status report for the ${REPORT_TIME} check.

Check results (${results.length} sites):
${summary}

Stats: ${upSites.length} UP, ${downSites.length} DOWN, avg response: ${avgResponse}ms

Write a Telegram message using these rules:
- Use Markdown formatting (bold with *text*, code with \`text\`)
- Start with a status emoji headline: ✅ All Clear / ⚠️ Issues Detected / 🚨 Critical
- Brief summary line
- List ALL sites, each on its own line:
  - ✅ for UP sites: show domain + response time
  - ❌ for DOWN sites: show domain + error
- If any DOWN: add a short "Action needed" section
- End with timestamp line
- Keep it scannable, not too long
- DO NOT use HTML, only Telegram Markdown

Return ONLY the message text, nothing else.`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  const data = await response.json();
  if (!response.ok) throw new Error(`Claude API error: ${JSON.stringify(data)}`);
  return data.content[0].text;
}

// ─── SEND TELEGRAM ───────────────────────────────────────────────────────────
async function sendTelegram(message) {
  const url = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: TELEGRAM_CHAT_ID,
      text: message,
      parse_mode: "Markdown",
      disable_web_page_preview: true,
    }),
  });

  const data = await response.json();
  if (!data.ok) throw new Error(`Telegram error: ${JSON.stringify(data)}`);
  console.log("Telegram message sent.");
}

// ─── MAIN ────────────────────────────────────────────────────────────────────
async function main() {
  if (!WEBSITES.length) {
    console.error("No websites configured. Set the WEBSITES env variable.");
    process.exit(1);
  }

  try {
    const results = await checkAll();
    console.log("Check complete.");

    const report = await generateReport(results);
    console.log("Report generated by Claude.");
    console.log("--- REPORT PREVIEW ---\n", report);

    await sendTelegram(report);
    console.log("Done!");
  } catch (err) {
    console.error("Monitor failed:", err);
    // Try to send error alert to Telegram
    try {
      await sendTelegram(`🔴 *Monitor Script Error*\n\`${err.message}\`\nPlease check GitHub Actions logs.`);
    } catch (_) {}
    process.exit(1);
  }
}

main();
